### ISSUE TITLE
Pointing to assets?

### ISSUE THREAD

**Issue by jpsmith5** [databio/refgenconf#28]
Is how I've constructed this the intended mechanism?

My refgenie config file:
```
genome_folder: $GENOMES
genome_server: http://refgenomes.databio.org

genomes:
  hg38:
    indexes:
      bowtie2: indexed_bowtie2
      hisat2: indexed_hisat2
    chrom_sizes: $GENOMES/hg38/hg38.chrom.sizes
```

So, for `rgc` `get_asset()` to obtain the `chrom_sizes` file, it requires the full path?

Before full path error:
```
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1551, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 504, in main
    res = _add_resources(args, res)
  File "pipelines/pepatac.py", line 460, in _add_resources
    res[asset] = rgc.get_asset(args.genome_assembly, asset)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 148, in get_asset
    raise IOError(msg)
OSError: Asset may not exist: hg38.chrom.sizes
```
Because other assets, like bowtie2 indices are relative, should additional assets also be relative to parent genome folder?

**Comment by nsheff** [comment]
it looks like you're using an old rendition of the format. it should be:

```
genomes:
  hg38:
    bowtie2:
      path: indexed_botwie2
    chrom_sizes:
      path: hg38.chrom.sizes
```

**Comment by jpsmith5** [comment]
Hmm. Okay, tried that but new messaging.

```
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1555, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 508, in main
    res = _add_resources(args, res)
  File "pipelines/pepatac.py", line 461, in _add_resources
    res[asset] = rgc.get_asset(args.genome_assembly, asset)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 140, in get_asset
    if strict_exists is not None and not check_exist(path):
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 108, in <lambda>
    check_exist=lambda p: os.path.exists(p) or is_url(p)):
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not YacAttMap
```

On `refgenconf 0.1.0` and `refgenie 0.4.0.dev0`

If I check to see which asset it's attempting to retrieve, I'm stuck back at trying to get the chrom_sizes file.

My refgenie config:

```
genome_folder: $GENOMES
genome_server: http://refgenomes.databio.org

genomes:
  hg38:
    bowtie2: 
      path: indexed_bowtie2
    hisat2: 
      path: indexed_hisat2
    chrom_sizes: 
      path: hg38.chrom.sizes
```

**Comment by nsheff** [comment]
Yeah @vreuter refgenconf is broken:

```
import  refgenconf
rgc = refgenconf.RefGenConf("test.yaml") 
rgc.genomes.hg38.chrom_sizes.path                                                                                 
Out[9]: 'hg38.chrom.sizes'
```

rgc.get_asset("hg38", "chrom_sizes")

~/code/refgenconf/refgenconf/refgenconf.py in get_asset(self, genome_name, asset_name, strict_exists, check_exist)
    138                 "Genome {} exists, but index {} is missing".
    139                 format(genome_name, asset_name))
--> 140         if strict_exists is not None and not check_exist(path):
    141             msg = "Asset may not exist: {}".format(path)
    142             for ext in [".tar.gz", ".tar"]:

~/code/refgenconf/refgenconf/refgenconf.py in <lambda>(p)
    106 
    107     def get_asset(self, genome_name, asset_name, strict_exists=True,
--> 108                   check_exist=lambda p: os.path.exists(p) or is_url(p)):
    109         """
    110         Get an asset for a particular assembly.

/usr/lib/python3.5/genericpath.py in exists(path)
     17     """Test whether a path exists.  Returns False for broken symbolic links"""
     18     try:
---> 19         os.stat(path)
     20     except OSError:
     21         return False

TypeError: argument should be string, bytes or integer, not YacAttMap

**Comment by jpsmith5** [comment]
Not sure if https://github.com/databio/refgenconf/commit/1472dca8ea5f6ca06b1eed1ac419685a5f4afbc5 should resolve this or not, but I'm still seeing an issue:

```
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1555, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 508, in main
    res = _add_resources(args, res)
  File "pipelines/pepatac.py", line 461, in _add_resources
    res[asset] = rgc.get_asset(args.genome_assembly, asset)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 134, in get_asset
    raise IOError(msg)
OSError: Asset may not exist: hg38.chrom.sizes
```

My refgenie config.yaml:
```
genome_folder: $GENOMES
genome_server: http://refgenomes.databio.org

genomes:
  hg38:
    bowtie2: 
      path: indexed_bowtie2
    hisat2: 
      path: indexed_hisat2
    chrom_sizes: 
      path: hg38.chrom.sizes
```

```
$ pip show refgenconf
Name: refgenconf
Version: 0.1.1.dev0
```

**Comment by nsheff** [comment]
yeah it's still not working.

**Comment by vreuter** [comment]
Point of origin matches but the upstream error differs.

**Comment by michalstolarczyk** [comment]
@jpsmith5, [this](https://github.com/databio/refgenconf/commit/9f254b907b6a622c69553a0fed8cf26be6fd08db) resolved it in my test case

**Comment by jpsmith5** [comment]
Okay, so that resolves the `chrom_sizes`, but now it's the bowtie2 index. Is my current yaml configuration not correct?

Error:
```
Traceback (most recent call last):
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 38, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'indexed_bowtie2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 399, in _genome_asset_path
    asset_data = genome[aname]
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 51, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 40, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'indexed_bowtie2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1555, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 508, in main
    res = _add_resources(args, res)
  File "pipelines/pepatac.py", line 461, in _add_resources
    res[asset] = rgc.get_asset(args.genome_assembly, asset)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 125, in get_asset
    asset_path = _genome_asset_path(self.genomes, genome_name, asset_name)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 402, in _genome_asset_path
    "Genome '{}' exists, but index '{}' is missing".format(gname, aname))
refgenconf.exceptions.MissingAssetError: Genome 'hg38' exists, but index 'indexed_bowtie2' is missing

```

My yaml again:
```
genome_folder: $GENOMES
genome_server: http://refgenomes.databio.org

genomes:
  hg38:
    bowtie2: 
      path: indexed_bowtie2
    hisat2: 
      path: indexed_hisat2
    chrom_sizes: 
      path: hg38.chrom.sizes

```

**Comment by michalstolarczyk** [comment]
Did you use `indexed_bowtie2` rather than `bowtie2` as the asset name in this case?

**Comment by michalstolarczyk** [comment]
to get the `indexed_bowtie2` value: `rgc.get_asset('hg38', 'bowtie2')`

**Comment by jpsmith5** [comment]
Hmm, so I'm working with @vreuter 's early implementation of this in PEPATAC, and it's using `BT2_IDX_KEY` as the asset.  Ah, so yes, if I print out what that represents, it's "indexed_bowtie2"

So should I be referring to it directly then as bowtie2, is there an internal value, like `BT2_IDX_KEY` that I could use instead?

**Comment by jpsmith5** [comment]
Same error.

```
asset: chrom_sizes
asset: bowtie2
Traceback (most recent call last):
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 38, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'indexed_bowtie2'
```

PEPATAC's usage:
```
for asset in ["chrom_sizes", "bowtie2"]:
        print("asset: {}".format(str(asset)))  # DEBUG
        res[asset] = rgc.get_asset(args.genome_assembly, asset)
```

**Comment by michalstolarczyk** [comment]
hmm, I don't know how is this even possible... it clearly says that you're using "bowtie2" as the asset_name

is the rest of the traceback the same as previously?

**Comment by vreuter** [comment]
```
(py3.5) vr @ ~
└─ $ ipython
^[[APython 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from refgenconf import RefGenConf                                                                                                                                                                   

In [2]: rgc = RefGenConf("/home/vr/pepatac_genconf.yaml")                                                                                                                                                   

In [3]: rgc.get_asset("hg38", "bowtie2")                                                                                                                                                                    
Out[3]: '/home/vr/genomes/hg38/indexed_bowtie2'

In [4]: rgc.get_asset("hg38", "chrom_sizes")                                                                                                                                                                
Out[4]: '/home/vr/genomes/hg38/hg38.chrom.sizes'

In [5]: quit                                                                                                                                                                                                
(py3.5) vr @ ~
└─ $ cat /home/vr/pepatac_genconf.yaml
genome_folder: $GENOMES
genome_server: http://refgenomes.databio.org

genomes:
  hg38:
    bowtie2: 
      path: indexed_bowtie2
    hisat2: 
      path: indexed_hisat2
    chrom_sizes: 
      path: hg38.chrom.sizes


```

**Comment by vreuter** [comment]
```
drwxrwxr-x 8 vr vr       4096 Jun  7 16:50 ./
drwxrwxr-x 9 vr vr       4096 Jun  7 16:50 ../
-rw-rw-r-- 1 vr vr  872949833 Mar  7  2017 GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
drwxrwxr-x 2 vr vr       4096 Dec  5  2018 gencode/
-rw-rw-r-- 1 vr vr   38464943 Mar  7  2017 gencode.v23.primary_assembly.annotation.gtf.gz
lrwxrwxrwx 1 vr vr         44 Dec  5  2018 genome_tiles -> /home/vr/resources/regions/genome_tiles/hg38/
-rw-rw-r-- 1 vr vr          0 Jun  7 16:40 hg38.chrom.sizes
lrwxrwxrwx 1 vr vr         16 Mar  7  2017 hg38.chromSizes -> hg38.chrom.sizes
-rw-rw-r-- 1 vr vr 3144230986 Mar  7  2017 hg38.fa
-rw-r--r-- 1 vr vr       7804 Mar  7  2017 hg38.fa.fai
-rw-rw-r-- 1 vr vr 1244267753 Mar  7  2017 hg38.gtf
drwxrwxr-x 3 vr vr       4096 Mar  8  2017 indexed_bismark_bt1/
drwxrwxr-x 3 vr vr       4096 Mar  8  2017 indexed_bismark_bt2/
drwxrwxr-x 2 vr vr       4096 Mar  7  2017 indexed_bowtie2/
drwxrwxr-x 2 vr vr       4096 Jun 16  2018 indexed_epilog/
drwxrwxr-x 2 vr vr       4096 Mar  8  2017 indexed_hisat2/
-rw-rw-r-- 1 vr vr       6050 Mar  8  2017 refgenie_commands.sh
-rw-rw-r-- 1 vr vr          0 Mar  8  2017 refgenie_completed.flag
-rw-rw-r-- 1 vr vr          0 Mar  8  2017 refgenie_failed.flag
-rw-rw-r-- 1 vr vr    1488305 Mar  8  2017 refgenie_log.md
-rw-rw-r-- 1 vr vr       2044 Mar  8  2017 refgenie_profile.tsv
-rw-rw-r-- 1 vr vr        224 Mar  8  2017 stats.tsv
```

**Comment by vreuter** [comment]
```
vr @ ~
└─ $ ll $GENOMES/hg38
total 5177228
drwxrwxr-x 8 vr vr       4096 Jun  7 16:50 ./
drwxrwxr-x 9 vr vr       4096 Jun  7 16:50 ../
-rw-rw-r-- 1 vr vr  872949833 Mar  7  2017 GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
drwxrwxr-x 2 vr vr       4096 Dec  5  2018 gencode/
-rw-rw-r-- 1 vr vr   38464943 Mar  7  2017 gencode.v23.primary_assembly.annotation.gtf.gz
lrwxrwxrwx 1 vr vr         44 Dec  5  2018 genome_tiles -> /home/vr/resources/regions/genome_tiles/hg38/
-rw-rw-r-- 1 vr vr          0 Jun  7 16:40 hg38.chrom.sizes
lrwxrwxrwx 1 vr vr         16 Mar  7  2017 hg38.chromSizes -> hg38.chrom.sizes
-rw-rw-r-- 1 vr vr 3144230986 Mar  7  2017 hg38.fa
-rw-r--r-- 1 vr vr       7804 Mar  7  2017 hg38.fa.fai
-rw-rw-r-- 1 vr vr 1244267753 Mar  7  2017 hg38.gtf
drwxrwxr-x 3 vr vr       4096 Mar  8  2017 indexed_bismark_bt1/
drwxrwxr-x 3 vr vr       4096 Mar  8  2017 indexed_bismark_bt2/
drwxrwxr-x 2 vr vr       4096 Mar  7  2017 indexed_bowtie2/
drwxrwxr-x 2 vr vr       4096 Jun 16  2018 indexed_epilog/
drwxrwxr-x 2 vr vr       4096 Mar  8  2017 indexed_hisat2/
-rw-rw-r-- 1 vr vr       6050 Mar  8  2017 refgenie_commands.sh
-rw-rw-r-- 1 vr vr          0 Mar  8  2017 refgenie_completed.flag
-rw-rw-r-- 1 vr vr          0 Mar  8  2017 refgenie_failed.flag
-rw-rw-r-- 1 vr vr    1488305 Mar  8  2017 refgenie_log.md
-rw-rw-r-- 1 vr vr       2044 Mar  8  2017 refgenie_profile.tsv
-rw-rw-r-- 1 vr vr        224 Mar  8  2017 stats.tsv

```

**Comment by vreuter** [comment]
@jpsmith5 can you try out `dev` now?

**Comment by jpsmith5** [comment]
I'll test it here shortly.  Update in a bit.

**Comment by jpsmith5** [comment]
Something weird happening from my side here.  It's showing $GENOMES, or /nm/t1/genomes/ as not existing.  Not inside of the pipeline call, just period.

```
$ ls $GENOMES
ls: cannot access /nm/t1/genomes/: No such file or directory
```

And thus for the pipeline call:
```
Changed status from initializing to running.

Loading config file: pipelines/pepatac.yaml

asset: chrom_sizes
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1555, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 508, in main
    res = _add_resources(args, res)
  File "pipelines/pepatac.py", line 461, in _add_resources
    res[asset] = rgc.get_asset(args.genome_assembly, asset)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 148, in get_asset
    raise IOError(msg)
OSError: Asset 'chrom_sizes' for genome 'hg38' doesn't exist; tried hg38.chrom.sizes and /nm/t1/genomes/hg38/hg38.chrom.sizes
Pipeline status: running
Starting cleanup: 0 files; 0 conditional files for cleanup

```

Very confused now.

**Comment by jpsmith5** [comment]
I was having issues getting logged in to Rivanna remotely, not sure how that would have disrupted my access to our default $GENOMES locations

**Comment by nsheff** [comment]
Yep those mounts are bad right now. You can use $PROJECT/genomes instead if you want to try, that is working at the moment.

**Comment by jpsmith5** [comment]
What's the actual path for $PROJECT? I don't have that as a standard var pointing to anything?

**Comment by jpsmith5** [comment]
Had a local GENOMES directory. Still getting KeyError on "bowtie2".

```
asset: chrom_sizes
asset: bowtie2
Traceback (most recent call last):
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 38, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'bowtie2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 409, in _genome_asset_path
    asset_data = genome[aname]
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 51, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 40, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'bowtie2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1555, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 513, in main
    _check_bowtie2_index(res.rgc, reference)
  File "pipelines/pepatac.py", line 327, in _check_bowtie2_index
    genome_assembly, "bowtie2", check_exist=os.path.isdir)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 129, in get_asset
    path = _genome_asset_path(self.genomes, genome_name, asset_name)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 412, in _genome_asset_path
    "Genome '{}' exists, but index '{}' is missing".format(gname, aname))
refgenconf.exceptions.MissingAssetError: Genome 'rCRSd' exists, but index 'bowtie2' is missing

```

**Comment by nsheff** [comment]
it's mounted in /project, but you should have the $PROJECT variable from the lab environment modules.

In the lab genomes folder you should have access to the index. 

btw /nm is back up.

**Comment by jpsmith5** [comment]
Still not seeing it up on my end.

```
$ ls $GENOMES
ls: cannot access /nm/t1/genomes/: No such file or directory
```

Was https://github.com/databio/refgenconf/commit/1472dca8ea5f6ca06b1eed1ac419685a5f4afbc5 supposed to resolve these errors?

```
Traceback (most recent call last):
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 38, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'indexed_bowtie2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 409, in _genome_asset_path
    asset_data = genome[aname]
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 51, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 40, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'indexed_bowtie2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1555, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 511, in main
    _check_bowtie2_index(res.rgc, args.genome_assembly)
  File "pipelines/pepatac.py", line 327, in _check_bowtie2_index
    genome_assembly, BT2_IDX_KEY, check_exist=os.path.isdir)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 129, in get_asset
    path = _genome_asset_path(self.genomes, genome_name, asset_name)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 412, in _genome_asset_path
    "Genome '{}' exists, but index '{}' is missing".format(gname, aname))
refgenconf.exceptions.MissingAssetError: Genome 'hg38' exists, but index 'indexed_bowtie2' is missing
```
My alternative $GENOMES dir
```
$ ls $GENOMES/hg38
GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz  hg38.fa      hg38_TSS.tsv         indexed_epilog  refgenie_commands.sh     refgenie_profile.tsv
gencode.v23.primary_assembly.annotation.gtf.gz      hg38.fa.fai  indexed_bismark_bt1  indexed_hisat2  refgenie_completed.flag  stats.tsv
hg38.chrom.sizes                                    hg38.gtf     indexed_bismark_bt2  mappability     refgenie_failed.flag     _TSS.tsv
hg38.chromSizes                                     hg38.idx     indexed_bowtie2      map.sub         refgenie_log.md
```

**Comment by jpsmith5** [comment]
Okay, get_asset() has to be "bowtie2", not indexed_bowtie2.  Seems like that was the source of the issue.  Confirming with more testing now.

**Comment by nsheff** [comment]
you have to use the key that is specified in the yaml file. (that key will point to the appropriate path).

I think it should actually be keyed on `bowtie2_index` or something... but you will have to use whatever your config is keyed on.

```
genomes:
  hg38:                         <--------------- that's the genome key.
    bowtie2:                    <--------------- that's the asset key.
      path: blahblahblah
````

**Comment by jpsmith5** [comment]
Yes, duh.  That clicked very shortly after. Thanks!
