### ISSUE TITLE
missing requirements

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#34]
```
pip install --user --upgrade refgenconf
Collecting refgenconf
  Downloading https://files.pythonhosted.org/packages/43/7c/12a275d5d113cf8af16ab8835619c2d16f6f96c2d287327a4f76d1984461/refgenconf-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/sfs/lustre/scratch/ns5bc/tmp/pip-install-0e90qak4/refgenconf/setup.py", line 10, in <module>
        with open("requirements/requirements-all.txt", "r") as reqs_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements/requirements-all.txt'
```

likely MANIFEST.in again

**Comment by nsheff** [comment]
fixed.

**Comment by nsheff** [comment]
@vreuter  can you give me permissions on pypi?

HTTPError: 403 Client Error: The user 'nsheff' isn't allowed to upload to project 'refgenconf'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy
