### ISSUE TITLE
behavior in get_asset for optional asset?

### ISSUE THREAD

**Issue by jpsmith5** [databio/refgenconf#38]
If I have an asset that is optional to a pipeline, it seems like the current configuration of the combination of `_get_asset()` and `_genome_asset_path` actually prevent the usage of `strict_exists` as anything other than `True`?

For example here:
```
path = _genome_asset_path(self.genomes, genome_name, asset_name)
if strict_exists is None or check_exist(path):
    return path
```

If I just want to report a warning or nothing at all about some asset, then `_genome_asset_path() `throws an exception before I'd get to the next line yes?

e.g. in a pipeline:
```
# REQ
for asset in ["chrom_sizes", BT2_IDX_KEY]:
    res[asset] = rgc.get_asset(args.genome_assembly, asset)
# OPT
asset = "tss_annotation"
if args.TSS_name:        
    res[asset] = os.path.abspath(args.TSS_name)
else:
    res[asset] = rgc.get_asset(args.genome_assembly, asset,
                                              strict_exists=False)
```

The resultant error when running if I do NOT have a tss_annotation asset.

python2
```
$ python2 pipelines/peppro.py --sample-name test --genome hg38 --input examples/data/test_r1.fq.gz --single-or-paired single -O ~/Downloads/peppro_example/
Changed status from initializing to running.

Loading config file: pipelines/peppro.yaml

Traceback (most recent call last):
  File "pipelines/peppro.py", line 2434, in <module>
    sys.exit(main())
  File "pipelines/peppro.py", line 627, in main
    res = _add_resources(args, res)
  File "pipelines/peppro.py", line 557, in _add_resources
    strict_exists=False)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 144, in get_asset
    path = _genome_asset_path(self.genomes, genome_name, asset_name)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 423, in _genome_asset_path
    "Genome '{}' exists, but index '{}' is missing".format(gname, aname))
refgenconf.exceptions.MissingAssetError: Genome 'hg38' exists, but index 'tss_annotation' is missing
Pipeline status: running
Starting cleanup: 0 files; 0 conditional files for cleanup

### Pipeline failed at:  (06-12 14:00:18) elapsed: 0.0 _TIME_

Total time: 0:00:00
Failure reason: Pipeline failure. See details above.

Changed status from running to failed.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 1744, in _exit_handler
    self.fail_pipeline(Exception("Pipeline failure. See details above."))
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 1638, in fail_pipeline
    raise e
Exception: Pipeline failure. See details above.
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 1744, in _exit_handler
    self.fail_pipeline(Exception("Pipeline failure. See details above."))
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 1638, in fail_pipeline
    raise e
Exception: Pipeline failure. See details above.
```

python3:
```
$ python3 pipelines/peppro.py --sample-name test --genome hg38 --input examples/data/test_r1.fq.gz --single-or-paired single -O ~/Downloads/peppro_example/

Changed status from initializing to running.

Loading config file: pipelines/peppro.yaml

Traceback (most recent call last):
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 38, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'tss_annotation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 420, in _genome_asset_path
    asset_data = genome[aname]
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 51, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 40, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'tss_annotation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipelines/peppro.py", line 2434, in <module>
    sys.exit(main())
  File "pipelines/peppro.py", line 627, in main
    res = _add_resources(args, res)
  File "pipelines/peppro.py", line 557, in _add_resources
    strict_exists=False)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 144, in get_asset
    path = _genome_asset_path(self.genomes, genome_name, asset_name)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 423, in _genome_asset_path
    "Genome '{}' exists, but index '{}' is missing".format(gname, aname))
refgenconf.exceptions.MissingAssetError: Genome 'hg38' exists, but index 'tss_annotation' is missing
Pipeline status: running
Starting cleanup: 0 files; 0 conditional files for cleanup

### Pipeline failed at:  (06-12 14:06:34) elapsed: 0.0 _TIME_

Total time: 0:00:00
Failure reason: Pipeline failure. See details above.

Changed status from running to failed.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/jps3dp/.local/lib/python3.6/site-packages/pypiper/manager.py", line 1744, in _exit_handler
    self.fail_pipeline(Exception("Pipeline failure. See details above."))
  File "/home/jps3dp/.local/lib/python3.6/site-packages/pypiper/manager.py", line 1638, in fail_pipeline
    raise e
Exception: Pipeline failure. See details above.

```

**Comment by vreuter** [comment]
Sorry for the ambiguity; the existence check is for the actual path that's returned. So in this case, no path can be returned at all since the asset key is missing. In other words, `strict_exists` governs how the case in which the genome/asset combo does resolve to a path, but that path doesn't exist. There's nothing currently in place to parameterize the behavior of the case you're outlining; right now the pipeline would need to catch this exception and react accordingly.

**Comment by jpsmith5** [comment]
Gotcha. That makes sense.  I'll adapt on my side.
