### ISSUE TITLE
python2 error

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#43]
```
 refgenie listr -c genomes.yaml 
Querying available assets from server: http://refgenomes.databio.org/assets
Traceback (most recent call last):
  File "./.local/bin/refgenie", line 11, in <module>
    sys.exit(main())
  File "/home/sheffien/.local/lib/python2.7/site-packages/refgenie/refgenie.py", line 464, in main
    pfx, genomes, assets = _exec_list(rgc, args.command == LIST_REMOTE_CMD)
  File "/home/sheffien/.local/lib/python2.7/site-packages/refgenie/refgenie.py", line 385, in _exec_list
    assemblies, assets = rgc.list_remote()
  File "/home/sheffien/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 256, in list_remote
    genomes, assets = _list_remote(url, order)
  File "/home/sheffien/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 541, in _list_remote
    genomes_data = _read_remote_data(url)
  File "/home/sheffien/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 575, in _read_remote_data
    with urllib.request.urlopen(url) as response:
AttributeError: 'module' object has no attribute 'request'
sheffien@zen:~$ 
```

**Comment by vreuter** [comment]
@michalstolarczyk did your commit that references this issue solve this?

**Comment by michalstolarczyk** [comment]
I believe thie commit above solved this issue. At least it's no longer valid in my tests:

```
[mjs5kd@udc-ba34-36 refgenconf](dev): python --version
Python 2.7.15 :: Anaconda, Inc.
[mjs5kd@udc-ba34-36 refgenconf](dev): refgenie list -c new.yaml 
refgenie 0.4.5-dev
Local genomes: 
Local recipes: epilog_index, bismark_bt2_index, bwa_index, bismark_bt1_index, fasta, star_index, gtf_anno, bowtie2_index, hisat2_index, kallisto_index, salmon_index
Local assets:

[mjs5kd@udc-ba34-36 refgenconf](dev):
```

**Comment by vreuter** [comment]
Cool deal
