### ISSUE TITLE
removing the last asset from a genome breaks the ability to add future assets

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#59]
remove all assets from a genome and your config file will get:

```
  mouse_chrM2x:
    assets: OrderedDict()
    genome_digest: e841943da75cb7d907a3f435dc1b7407394797815ae44686
config_version: 0.3
genome_folder: /ext/yeti/refgenomes
```

```
refgenie pull mouse_chrM2x/bowtie2_index
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 649, in main
    unpack=not args.no_untar)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 494, in pull_asset
    [self._check_asset_digest(genome, x) for x in archive_data[CFG_ASSET_PARENTS_KEY] if
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 495, in <listcomp>
    CFG_ASSET_PARENTS_KEY in archive_data]
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 769, in _check_asset_digest
    allow_incomplete=not self.is_asset_complete(genome, asset, tag))
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 725, in is_asset_complete
    tag_data = self[CFG_GENOMES_KEY][genome][CFG_ASSETS_KEY][asset][CFG_ASSET_TAGS_KEY][tag]
TypeError: string indices must be integers

```

is there a way to remove a genome? Maybe there doesn't need to be, but then what do we do if the last asset is removed? at the moment this creates a broken entry in the config file that cannot be rescued with the CLI.

**Comment by michalstolarczyk** [comment]
the genome should get removed with the last removed asset. And this is what happens in my tests:

```
[mstolarczyk@MichalsMBP test_genomes]: refgenie remove -c genomes.yaml mouse_chrM2/bowtie2_index
Remove 'mouse_chrM2/bowtie2_index:default'? [y/N] y
Last tag for asset 'bowtie2_index' has been removed, removing asset directory
Successfully removed entities:
- /Users/mstolarczyk/Desktop/testing/test_genomes/mouse_chrM2/bowtie2_index/default/
- /Users/mstolarczyk/Desktop/testing/test_genomes/mouse_chrM2/bowtie2_index
[mstolarczyk@MichalsMBP test_genomes]: refgenie remove -c genomes.yaml mouse_chrM2/fasta
Remove 'mouse_chrM2/fasta:default'? [y/N] y
Last tag for asset 'fasta' has been removed, removing asset directory
Last asset for genome 'mouse_chrM2' has been removed, removing genome directory
Successfully removed entities:
- /Users/mstolarczyk/Desktop/testing/test_genomes/mouse_chrM2/fasta/default
- /Users/mstolarczyk/Desktop/testing/test_genomes/mouse_chrM2/fasta
- /Users/mstolarczyk/Desktop/testing/test_genomes/mouse_chrM2
[mstolarczyk@MichalsMBP test_genomes]: refgenie list -c genomes.yaml
Local genomes: rCRSd
Local recipes: fasta, bowtie2_index, bwa_index, hisat2_index, bismark_bt2_index, bismark_bt1_index, kallisto_index, salmon_index, epilog_index, star_index, gencode_gtf, ensembl_gtf, ensembl_rb, refgene_anno, feat_annotation
Local assets:
  rCRSd: fasta.chrom_sizes:test, fasta.fai:test, fasta.fasta:test
```

**Comment by nsheff** [comment]
wait I think I see the problem.... it's not with removing, it's with a failed first build attempt.....

**Comment by michalstolarczyk** [comment]
I did not pull nor remove, but I checked the config file and the genome was gone

**Comment by nsheff** [comment]
I was mistaken, it's not related to `remove`. Here's the problem:

try to build a fasta asset with an unzipped fasta:

```
refgenie build -g rCRSd fasta --fasta /project/shefflab/www/refgenie_raw/mouse_chrM2x.fa
```

it says:
```
> `gzip -d /ext/yeti/refgenomes/rCRSd/fasta/default/rCRSd.fa.gz` (11748)

gzip: /ext/yeti/refgenomes/rCRSd/fasta/default/rCRSd.fa.gz: not in gzip format
<pre>
</pre>
Command completed. Elapsed time: 0:00:00. Running peak memory: 0GB.  
  PID: 11748;	Command: gzip;	Return code: 1;	Memory used: 0.0GB


### Pipeline failed at:  (09-11 11:43:23) elapsed: 0.0 _TIME_

Total time: 0:00:00
Failure reason: Subprocess returned nonzero result. Check above output for details
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 621, in main
    refgenie_build(rgc, asset_list[0]["genome"], asset_list, args)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 459, in refgenie_build
    build_asset(genome, asset_key, asset_tag, asset_build_package, outfolder, specific_args, **input_assets)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 377, in build_asset
    pm.run(command_list_populated, target, container=pm.container)
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/manager.py", line 777, in run
    self.callprint(cmd_i, shell, lock_file, nofail, container)
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/manager.py", line 1028, in callprint
    self._triage_error(SubprocessError(msg), nofail)
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/manager.py", line 2131, in _triage_error
    self.fail_pipeline(e)
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/manager.py", line 1660, in fail_pipeline
    raise exc
pypiper.exceptions.SubprocessError: Subprocess returned nonzero result. Check above output for details
```


and now adds this to the genome config:
```
  rCRSd:
    assets: OrderedDict()
    genome_digest: e841943da75cb7d907a3f435dc1b7407394797815ae44686
```

which breaks everything else

```

refgenie list
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 652, in main
    pfx, genomes, assets, recipes = _exec_list(rgc, args.command == LIST_REMOTE_CMD, args.genome)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 524, in _exec_list
    assemblies, assets = rgc.list_local(genome=genome)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 324, in list_local
    return genomes_str, self.assets_str(genome=genome, order=order)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 143, in assets_str
    return "\n".join([make_line(g, self[CFG_GENOMES_KEY][g][CFG_ASSETS_KEY]) for g in refgens])
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 143, in <listcomp>
    return "\n".join([make_line(g, self[CFG_GENOMES_KEY][g][CFG_ASSETS_KEY]) for g in refgens])
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 953, in _make_genome_assets_line
    tagged_assets = asset_sep.join(sorted(_make_asset_tags_product(assets, genome_tag_delim), key=order))
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 966, in _make_asset_tags_product
    for name, asset in list(assets.items()):
AttributeError: 'str' object has no attribute 'items'

```

**Comment by nsheff** [comment]
I thought it was the remove thing because I had just been doing that.
