### ISSUE TITLE
list_remote broken. 

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#81]
I just did this:

```
refgenie init -c refgenie.yaml
```

Now in python:

```
import refgenconf
rgc = refgenconf.RefGenConf("refgenie.yaml")

>>> rgc
RefGenConf
genome_servers: ['http://refgenomes.databio.org']
config_version: 0.3
genome_folder: /home/sheffien
genomes: OrderedDict()

>>> rgc.list_remote()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sheffien/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 396, in list_remote
    url = get_url(self[CFG_SERVERS_KEY], API_ID_ASSETS)
  File "/home/sheffien/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 385, in <lambda>
    def list_remote(self, genome=None, order=None, get_url=lambda server, id: construct_request_url(server, id)):
  File "/home/sheffien/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 1298, in construct_request_url
    return server_url + _get_server_endpoints_mapping(server_url)[operation_id]
  File "/home/sheffien/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 1312, in _get_server_endpoints_mapping
    json = _download_json(url + "/openapi.json")
TypeError: can only concatenate list (not "str") to list
```

need to add a unit test for this?

**Comment by nsheff** [comment]
also this is a little weird:

```
>>> rgc.list_local()
('', '')
```

**Comment by nsheff** [comment]
interestingly, it works from the commandline with `refgenie listr`

**Comment by stolarczyk** [comment]
fixed and changed to `listr()` and `list` following `refgenie listr` and `refgenie list` in CLI
