### ISSUE TITLE
TypeError: tag must be str; got unicode

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#89]
Not sure if this is related to #86 

On python2:

```
refgenie pull -c refgenie.yaml rCRSd/fasta
Downloading URL: http://refgenomes.databio.org/v2/asset/rCRSd/fasta/archive
Download complete: /home/nsheff/sandbox/rCRSd/fasta__default.tgz
Extracting asset tarball and saving to: /home/nsheff/sandbox/rCRSd/fasta/default
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python2.7/site-packages/refgenie/refgenie.py", line 652, in main
    rgc.pull(a["genome"], a["asset"], a["tag"],unpack=not args.no_untar)
  File "/home/nsheff/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 742, in pull
    for attr in ATTRS_COPY_PULL if attr in archive_data})
  File "/home/nsheff/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 824, in update_tags
    if _check_insert_data(tag, str, "tag"):
  File "/home/nsheff/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 1416, in _check_insert_data
    name, datatype.__name__, type(obj).__name__))
TypeError: tag must be str; got unicode
```

**Comment by nsheff** [comment]
the same thing works in python 3.
