### ISSUE TITLE
malformed string error

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#90]
in python 3, try to re-pull an bowtrie2 index:

```
 refgenie pull rCRSd/bowtie2_index -c refgenie.yaml
Replace existing (/home/nsheff/sandbox/rCRSd/bowtie2_index/default)? [y/N] y
Downloading URL: http://refgenomes.databio.org/v2/asset/rCRSd/bowtie2_index/archive
Download complete: /home/nsheff/sandbox/rCRSd/bowtie2_index__default.tgz                                                           
Extracting asset tarball and saving to: /home/nsheff/sandbox/rCRSd/bowtie2_index/default
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.7/site-packages/refgenie/refgenie.py", line 652, in main
    rgc.pull(a["genome"], a["asset"], a["tag"],unpack=not args.no_untar)
  File "/home/nsheff/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 742, in pull
    for attr in ATTRS_COPY_PULL if attr in archive_data})
  File "/home/nsheff/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 825, in update_tags
    self[CFG_GENOMES_KEY][genome][CFG_ASSETS_KEY][asset].setdefault(CFG_ASSET_TAGS_KEY, PXAM())
AttributeError: 'str' object has no attribute 'setdefault'
```

config looks like:

```
  rCRSd:
    assets:
      fasta:
        tags:
          default:
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            asset_children: ['rCRSd/bowtie2_index:default', 'rCRSd/star_index:default']
            seek_keys:
              fasta: rCRSd.fa
              fai: rCRSd.fa.fai
              chrom_sizes: rCRSd.chrom.sizes
            asset_parents: []
            asset_path: fasta
        default_tag: default
      bowtie2_index: OrderedDict()

```

**Comment by stolarczyk** [comment]
current behavior:

```
[mjs5kd@udc-ba36-36 genomes]: refgenie pull rCRSd/bowtie2_index -c g.yaml
Replace existing (/sfs/qumulo/qhome/mjs5kd/testing/genomes/rCRSd/bowtie2_index/default)? [y/N] y
Downloading URL: http://refgenomes.databio.org/v2/asset/rCRSd/bowtie2_index/archive
Download complete: /sfs/qumulo/qhome/mjs5kd/testing/genomes/rCRSd/bowtie2_index__default.tgz
Extracting asset tarball and saving to: /sfs/qumulo/qhome/mjs5kd/testing/genomes/rCRSd/bowtie2_index/default
Traceback (most recent call last):
  File "/home/mjs5kd/.local/bin/refgenie", line 8, in <module>
    sys.exit(main())
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/refgenie/refgenie.py", line 652, in main
    rgc.pull(a["genome"], a["asset"], a["tag"],unpack=not args.no_untar)
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 745, in pull
    for attr in ATTRS_COPY_PULL if attr in archive_data})
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 832, in update_tags
    [asset], CFG_ASSET_TAGS_KEY, PXAM())
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 1604, in _safe_setdef
    _raise_not_mapping(mapping, "Cannot update; Section '{}' ".format(attr))
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/refgenconf/refgenconf.py", line 1611, in _raise_not_mapping
    "a previous error".format(type(mapping).__name__)
refgenconf.exceptions.GenomeConfigFormatError: Cannot update; Section 'tags' is not a mapping but 'str'. This is usually a result of a previous error; For config format documentation please see http://refgenie.databio.org/en/latest/genome_config/
```

simulated config:

```yaml
genome_servers: ['http://refgenomes.databio.org']
config_version: 0.3
genome_folder: /sfs/qumulo/qhome/mjs5kd/testing/genomes
genomes:
  rCRSd:
    assets:
      fasta:
        tags:
          default:
            asset_path: fasta
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            asset_parents: []
            seek_keys:
              fasta: rCRSd.fa
              fai: rCRSd.fa.fai
              chrom_sizes: rCRSd.chrom.sizes
            asset_children: ['rCRSd/bowtie2_index:default']
        default_tag: default
      bowtie2_index: test
```
